# This file should be generated by running:
# nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# Run this command on your DESKTOP to get the correct hardware configuration
# Then copy the output here.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # PLACEHOLDER: Replace this entire file with your actual hardware configuration
  # You can generate it by running the command mentioned above on your NixOS system
  
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  # Swap configuration
  # swapDevices = [ ];

  # CPU microcode updates (uncomment for your CPU)
  # hardware.cpu.intel.updateMicrocode = true;
  # hardware.cpu.amd.updateMicrocode = true;

  # NVIDIA drivers (uncomment if you have an NVIDIA GPU)
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = false;
  #   open = false;
  #   nvidiaSettings = true;
  # };
}
