# This file should be generated by running:
# nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# Run this command on your NixOS machine to get the correct hardware configuration
# Then copy the output here.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # PLACEHOLDER: Replace this entire file with your actual hardware configuration
  # You can generate it by running the command mentioned above on your NixOS system
  
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  # Swap configuration
  # swapDevices = [ ];

  # CPU microcode updates
  # hardware.cpu.intel.updateMicrocode = true;
  # hardware.cpu.amd.updateMicrocode = true;
}
